development:
  adapter: mysql2 
  database: timetable_dev
  username: root
  password:

test:
  adapter: mysql2 
  database: timetable_test
  username: root
  password:

production:
  adapter: mysql2 
  database: timetable
  username: root
  password:
